### ISSUE TITLE
Firefox Main Back Button Not Showing Arrow

### ISSUE THREAD

**Issue by Kandelai** [EliverLara/Juno#1]
Hello, love the theme, but running Firefox version 65 and noticed the main/back button only shows an arrow if you mouse over it, else it is just a big circle. Can you add an arrow to it?

![screenshot-20190130125923-207x144](https://user-images.githubusercontent.com/39681298/52012788-54e9a680-2490-11e9-8e2c-92af9967c068.png)

**Comment by Accelyte** [comment]
would also like to see this fixed, on Ocean it's barely visible
