### ISSUE TITLE
Selected option colour is almost the same as text colour

### ISSUE THREAD

**Issue by Accelyte** [EliverLara/Juno#12]
Using Juno-Ocean:
In Firefox, when the "Highlight All" option is selected, the selected colour is almost the same as the text underneath it, making it unreadable.
![Screenshot from 2020-02-18 19-16-28](https://user-images.githubusercontent.com/21363469/74771276-c0620a00-5285-11ea-81d1-e13f7752fbec.png)

**Comment by EliverLara** [comment]
You could use [firefox-color](https://color.firefox.com/) and apply [this custom theme](https://color.firefox.com/?theme=XQAAAAImAQAAAAAAAABBqYhm849SCia2CaaEGccwS-xNKlhOfcHVcVoCaN5_zFed69d2MvCSDNAWxuAKn8ihIs13le9vaJAg81Dq_K2aPdOXWlzAjQ_cHmS6vPYEPmxaM_8Snwv3AHJWRa2vCLP9veNxGkcBW2PwfU0KiYze0hXq4DtEWY4GdQVD_1e6VRQ8_Kx0Fd_7kez4FTzhSYqoq6mXpAxXyvXZFNtl8IAVyCpURSLatbgPmniD3uI0w6uhz7yWPNOr6BmGYcsRiUT_F5T16ar8DCpd) to get a better looking.
