### ISSUE TITLE
WiFi selection menu is still white

### ISSUE THREAD

**Issue by Accelyte** [EliverLara/Juno#13]
Using Juno-Ocean:
The WiFi selection menu doesn't seem to be themed?
![Screenshot from 2020-02-18 20-17-29](https://user-images.githubusercontent.com/21363469/74774914-7af50b00-528c-11ea-87c5-2e027798330f.png)

**Comment by EliverLara** [comment]
Hi, It seems to be fine for me:

![Captura de pantalla de 2020-02-19 11-31-38](https://user-images.githubusercontent.com/9838260/74858834-98b58500-530b-11ea-913b-e411921aa018.png)

Could you tell me what is your gnome-shell version, please ?

**Comment by Accelyte** [comment]
I'm currently using Pop!_OS 18.04, which says runs GNOME 3.28.2

**Comment by EliverLara** [comment]
Fixed!
