### ISSUE TITLE
Is the top bar supposed to be transparent when windows are maximized?

### ISSUE THREAD

**Issue by eeshugerman** [EliverLara/Juno#14]
Depending on the wallpaper it can look pretty strange..
![image](https://user-images.githubusercontent.com/25518211/76685968-6aab2400-65dd-11ea-827c-90fe49d65525.png)

I have the same issue with Nordic.

(EDIT: Updated screenshot with different wallpaper to better demonstrate the effect.)

**Comment by EliverLara** [comment]
I have reduced that transparency.
