### ISSUE TITLE
Week numbers and weather hours are illegible in Gnome 3.36

### ISSUE THREAD

**Issue by argosatcore** [EliverLara/Juno#15]
First, thank you Eliver for designing such a beautiful theme. The only issue that I've found so far is related to the weeks' numbers and the weather's hours displayed on the calendar. They are way too dark to be readable. I think that changing their actual color for a lighter one (like white o a light green) might do the trick. I include here a picture of the issue to better illustrate my point.

![Screenshot from 2020-05-17 17-41-48](https://user-images.githubusercontent.com/64110504/82163139-7f6a9900-9866-11ea-9f48-b2bf5f2c012d.png)

**Comment by EliverLara** [comment]
Fixed!
