### ISSUE TITLE
Juno Ocean

### ISSUE THREAD

**Issue by poxin13** [EliverLara/Juno#16]
Been trying to lighten the font-color a bit in Juno Ocean, but doesn't ever seem to take effect. Pretty sure I'm not modifying the correct css entry.

In `gtk-3.0\*.css` I am updating `@define-color theme_text_color #6F7678;`

Any help would be appreciated. The best dark theme I've come upon after trying a few dozen but the font the desktop/apps/etc is a bit too dark for me to read.

**Comment by EliverLara** [comment]
Hi, to change the text color you must edit the `$text_color` and `$fg_color` variables within the `gtk-3.0/_colors.scss` file and then recompile the whole theme by running in your terminal `sass gtk.scss gtk.css`

**Comment by szutsattila** [comment]
Hey, I tried doing what you recommended, but I have seen no results. Is this still the recommended way to change the text colors? Not every color is dark, just for example the text in my ArcMenu.

**Comment by szutsattila** [comment]
![This is an example, how it looks. ](https://user-images.githubusercontent.com/45080765/112951355-8d05d600-913b-11eb-9769-adbbc90dc175.png)

I'd like the text to be a bit whiter, how can I achieve this?

**Comment by EliverLara** [comment]
@szutsattila, to change those colors you must edit the `$fg_color` variable  within the `gnome-shell/_colors.scss` file and then recompile the whole shell theme by running in your terminal `sass gnome-shell.scss gnome-shell.css`
