### ISSUE TITLE
No folder icons in context menu ?

### ISSUE THREAD

**Issue by its-mXc** [EliverLara/Juno#19]
I just wanted to bring to your attention that there are no colors in folder colors in context menu.

![Screenshot from 2020-07-05 16 10 43](https://user-images.githubusercontent.com/52538450/86530888-5b2c4f80-beda-11ea-987a-66741420e334.png)

**Comment by its-mXc** [comment]
Oh i forgot to mention, the os is elementary os 5.1.5 Hera

**Comment by EliverLara** [comment]
That was fixed in 3dbdbb9f20fcc617cf5960e57185568a053c7e3e
