### ISSUE TITLE
Name of icon theme at gnome-look.org?

### ISSUE THREAD

**Issue by patri9ck** [EliverLara/Juno#24]
This is a screenshot of Juno-ocean at gnome-look.org: https://cdn.pling.com/img/c/5/7/e/09632dbaff18cbdca7943963aec1c24a7abbf6c9e67556dc4b180b2414120d495a74.png

What is the name of the icon theme? I think it looks great with Juno-ocean.

**Comment by EliverLara** [comment]
Those are [Flatery icons](https://www.gnome-look.org/p/1332404/)
