### ISSUE TITLE
tittle bar not  working on some apps

### ISSUE THREAD

**Issue by cyrstem** [EliverLara/Juno#3]
hi, why  do  the  june theme dont work on some apps 
 in manjaro 
![Screenshot from 2019-09-14 23-00-47](https://user-images.githubusercontent.com/2263696/64916497-b28ee280-d743-11e9-9c93-a91c244e9816.png)
![Screenshot from 2019-09-14 23-01-11](https://user-images.githubusercontent.com/2263696/64916498-b3c00f80-d743-11e9-8319-51a7167f0923.png)
is there a way to fix this

**Comment by EliverLara** [comment]
Hi, What is your gnome version?

**Comment by cyrstem** [comment]
hi i fix it by installing again  dont know what happen  the first time i have gnome 3 

thanks anyway
