### ISSUE TITLE
Incorrect display of the dock on Gnome 40

### ISSUE THREAD

**Issue by alessiocelentano** [EliverLara/Juno#31]
Hi.

The theme is awesome, but Gnome 40 was released and there some things that look bad. The main problem is the dock, it would be nicer if it looked like the ones of the default theme. Another small problem is the calendar widget (hover on it)
![screenshot](https://user-images.githubusercontent.com/48618881/115770551-262bb380-a3ad-11eb-8aad-44c9ff9d5dec.png)

**Comment by eosdev-x** [comment]
Having the same issue, the only theme I'm not having it with is Orchis.

**Comment by EliverLara** [comment]
Fixed!
