### ISSUE TITLE
Lock screen password

### ISSUE THREAD

**Issue by backbone24** [EliverLara/Juno#38]
Hello,

I love theme, thank you for designing it.

I have one minor issue on the lock screen. The password always sticks out to the left of the password field. I have attached two images of the lock screen in two different resolutions.

![IMG_8795](https://user-images.githubusercontent.com/9007215/130151010-392a5127-0867-460a-944f-4faaaf2b6632.jpg)
![IMG_8796](https://user-images.githubusercontent.com/9007215/130151012-46e6850b-90b1-4667-8372-77ae5064cb7a.jpg)

All the best,
Benny

**Comment by EliverLara** [comment]
That was fixed in 35f6c18443db4e8cd187099a4f8112214480be7f
