### ISSUE TITLE
Icons theme doesn't work

### ISSUE THREAD

**Issue by yahia20** [EliverLara/Juno#39]
when coping the icons theme Juno-ocean-standard-buttons folder into /use/share/icons ,and choosing it via tweak tools, the icons of everything becomes the default gnome icons.

when I tried fixing it i noticed that there were no folder like x24 x32 x64 .... like in all of the other themes only assets and css file

using gnome 3.38.4 on pop os 20.04 kernel 5.11.0-7620-generic

**Comment by yahia20** [comment]
edit pop os 21.04

**Comment by EliverLara** [comment]
Hi, this theme does not provide the icon theme, it needs to be downloaded seperately from the gtk theme, the icons showed in screenshot are [flatery-icons](https://store.kde.org/p/1332404/)

**Comment by yahia20** [comment]
ok thanks
