### ISSUE TITLE
Evolution White Text White background

### ISSUE THREAD

**Issue by rgillette** [EliverLara/Juno#4]
After the upgrade to gnome shell 3.34 I am unable to read emails in Evolution. I am able to read the signature due to it having custom colors. 

Evolution Ver. 3.34.0-1.fc31
Gnome-Shell Ver. 3.34.0-1.fc31

![Screenshot from 2019-09-20 07-40-09](https://user-images.githubusercontent.com/36198873/65335999-5c260780-db7a-11e9-8927-de0cd65cba82.png)

**Comment by dabbill** [comment]
I have tried a few other dark themes. This seems to be an issue with pretty much every dark theme I have tried.

**Comment by EliverLara** [comment]
I don't have gnome 3.34 yet, at the moment I can't reproduce the issue.

**Comment by dabbill** [comment]
Is there a way I can do some debugging for you?
