### ISSUE TITLE
Icon Theme + Vs Code Theme

### ISSUE THREAD

**Issue by HeIIow2** [EliverLara/Juno#59]
Heyy,

I am in love with the theme in the ocean branch!

2 Things:

1. What is the icon theme you are using.
2. You mentioned those themes are inspired by vs-code themes. Do you mind linking those vs-code themes? I really wanna have this theme.

Thanks btw <3333

**Comment by melroy89** [comment]
The icon theme used in the screenshots is called Flatery: https://store.kde.org/p/1332404/

**Comment by HeIIow2** [comment]
Hey thanks I really like that icon theme <333
