### ISSUE TITLE
High CPU usage on xfce4-panel in XFCE v4.18

### ISSUE THREAD

**Issue by melroy89** [EliverLara/Juno#61]
Since I upgraded to XFCE 4.18 I noticed **high CPU usage** of the `xfce4-panel` process.

The root-cause was in Panel->Panel Preferences -> Appearance tab-> Background style-> "None (use system style)".

The moment I changed this to "Solid color" instead, the high CPU usage issue went away..

I think you need to look into the default panel style, especially the background.. 

Thanks in advance...

Related: https://unix.stackexchange.com/questions/500771/xfce4-panel-and-xorg-using-100-cpu-when-the-panel-background-set-to-none-use (but not the same theme, but related issue)

**Comment by EliverLara** [comment]
Hi, I'm so sorry for the very late response, Could you please tell me how can I see such behaviour? I've testing my themes and I've never faced that issue, I would be amazing if you could help me.

**Comment by melroy89** [comment]
So I use Juno-v40 with Linux Mint 20 (XFCE).

Then I go to the Panel Preferences and select "none" as background style:

![image](https://github.com/EliverLara/Juno/assets/628926/a529dd0f-f9e6-4f07-82a1-1ffd30ce749f)

And this is causing the xfce4-panel use about 20% CPU (constant usage!):

![image](https://github.com/EliverLara/Juno/assets/628926/3a68be5d-68ad-4ada-869c-58d9ab616fb5)

**Comment by EliverLara** [comment]
Thank you so much for your help, Could you please make me a big favor and check if replacing the file `Juno/gtk-3.0/gtk.css` with  [this one](https://github.com/EliverLara/Juno/files/12841941/gtk.zip)(extracted) fixes the issue, please?

**Comment by melroy89** [comment]
I  need to switch between another theme and your GTK  theme(at Appearance in XFCE) to be sure the new gtk.css file gets loaded. But yes, it seems to be fixed! 🥳 

It's now around 0.7% CPU load, sometimes 0.0%.

When switching back to the old version (and switching themes to another theme and back to Juno v40) it seems to be returning. Meaning that I can reproduce the problem on the old version and your new css file the issue seems to be fully resolved.

_One side note:_ I did copied to: `Juno-v40/gtk-3.0/` (so **not** `Juno`), because I'm using v40. But I copied your file to the v40 version. I hope that doesn't matter too much. Ideally you may want to patch all your versions 👍🏽 .

**Comment by EliverLara** [comment]
Thank you so much for all your help @melroy89 I'm so grateful with you, and yes I'll be patching all my themes and versions, thank you so much!

**Comment by melroy89** [comment]
Thank you as well for coming back and solving the problem!

**Comment by CamsShaft** [comment]
HAHAHA I can't believe this worked. So stupid. Thank you!

**Comment by melroy89** [comment]
> HAHAHA I can't believe this worked. So stupid. Thank you!

It should be patched already right? Or do you still need the workaround?

**Comment by CamsShaft** [comment]
> > HAHAHA I can't believe this worked. So stupid. Thank you!
> 
> It should be patched already right? Or do you still need the workaround?

Actually no it's all good. As soon as I switched to stock background my laptop calmed down. I just installed xfce and was busy configuring and noticed the cpu graph on the panel I JUST put there earlier was going haywire. I'm sure I wouldn't have noticed it for a while. There's a ton of processes in the task manager but only like 4 were running
