### ISSUE TITLE
Please share icon theme you are using

### ISSUE THREAD

**Issue by nesslopz** [EliverLara/Juno#7]
Hi! Your theme is amazing! :clap: :clap: 
This is not an issue, but please in theme description can you tell us which icon-theme are you using please. :pray: 
And probably some extra-configuration required to get complete style :+1:

**Comment by EliverLara** [comment]
Hi, here you have:

[Juno-Folders](https://github.com/EliverLara/Juno/files/4003331/Juno-Folders.zip)
[Icons](https://www.pling.com/p/1305251/)
